web/router.ex
defmodule Demo.Router do
  use Phoenix.Router

  scope "/" do
    # Use the default browser stack.
    pipe_through :browser

    get "/", Demo.PageController, :index, as: :index
    get "/demo", Demo.PageController, :getdemo, as: :demo
    post "/demo", Demo.PageController, :postdemo, as: :demo
    get "/s3", Demo.PageController, :s3, as: :s3
  end

  # Other scopes may use custom stacks.
  # scope "/api" do
  #   pipe_through :api
  # end
end

web/controllers/page_controller.ex
defmodule Demo.PageController do
  use Phoenix.Controller
  alias Poison, as: JSON

  plug :action

  def index(conn, _params) do
    render conn, "index"
  end

  def getdemo(conn, _params) do
    conn
    |> put_layout("application")
    |> render "demo"
  end

  def postdemo(conn, %{"file" => file}) do
    {:ok, cdyr} = File.cwd()
    File.copy(file.path, cdyr <> "/priv/static/" <> file.filename)
    redirect conn, "/"
  end

  def s3(conn, _params) do
    asd = HTTPoison.get! "https://api.digitalocean.com/v2/droplets", %{"Authorization" => "Bearer d6ac7dab4545f743dab50562054116480968a8a860260ddd24a8fcc4fb9162ea"}
    IO.puts "#{to_string(JSON.encode!(asd))}"
    json conn, "#{JSON.encode!(asd)}"
  end

  def not_found(conn, _params) do
    render conn, "not_found"
  end

  def error(conn, _params) do
    render conn, "error"
  end
end

web/views/layout_view.ex
defmodule Demo.LayoutView do
  use Demo.Views

end

web/views/page_view.ex
defmodule Demo.PageView do
  use Demo.Views

end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="/css/phoenix.css">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><a href="https://github.com/phoenixframework/phoenix">Get Started</a></li>
        </ul>
        <span class="logo"></span>
      </div>

      <%= @inner %>

      <div class="footer">
        <p><a href="http://phoenixframework.org">phoenixframework.org</a></p>
      </div>

    </div> <!-- /container -->
  </body>
</html>

web/templates/page/demo.html.eex
<form action="<%= demo_path(:postdemo) %>" enctype="multipart/form-data" method="post">
  <input type="hidden" name="_method" value="POST">
  <input type="file" name="file">
  <input type="submit" value="Subir">
</form>

web/templates/page/error.html.eex
Something went wrong

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">Phoenix is an Elixir Web Framework targeting full-featured, fault tolerant applications with realtime functionality.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://api.phoenixframework.org/">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/issues?state=open">Issues</a>
      </li>
      <li>
        <a href="irc://irc.freenode.net/elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/chris_mccord">@chris_mccord</a>
      </li>
    </ul>
  </div>
</div>

web/templates/page/not_found.html.eex
The page you are looking for does not exist